server:
  port: 8089
spring:
  application:
    name: springboot-redis
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    connect-timeout: 6000
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接

    #===========jedis配置方式=============================================
    #    jedis:
    #      pool:
    #        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
    #        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
    #        max-idle: 10      # 连接池中的最大空闲连接
    #        min-idle: 5       # 连接池中的最小空闲连接
    #    cluster:
    #      nodes:
    #        - IP地址:6379
    #        - IP地址:6380
    #        - IP地址:6381
    #        - IP地址:6382
    #        - IP地址:6383
    #        - IP地址:6384
    #      max-redirects: 3  # 获取失败 最大重定向次数


#







