server:
  port: 8081
spring:
#  task:
#    scheduling:
#      thread-name-prefix: nzc-schedule- #线程名前缀
#      pool:
#        size: 10 #核心线程数
     # shutdown:
     #  await-termination: true #执行程序是否应等待计划任务在关机时完成。
     #   await-termination-period:  #执行程序应等待剩余任务完成的最长时间。


  redis:
    host: 47.113.227.254
    password: 000415

